// Standardized Error Codes
// Clients match on `code` instead of parsing `message` strings.

export const ErrorCodes = {
  // Generic
  NOT_FOUND: 'NOT_FOUND',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Store
  STORE_SUSPENDED: 'STORE_SUSPENDED',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  PLAN_EXPIRED: 'PLAN_EXPIRED',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',

  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INSUFFICIENT_INVENTORY: 'INSUFFICIENT_INVENTORY',
  PRODUCT_UNPUBLISHED: 'PRODUCT_UNPUBLISHED',

  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_FULFILLED: 'ORDER_ALREADY_FULFILLED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
  ORDER_NOT_FULFILLED: 'ORDER_NOT_FULFILLED',

  // Coupon
  INVALID_COUPON: 'INVALID_COUPON',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_USAGE_EXCEEDED: 'COUPON_USAGE_EXCEEDED',

  // Customer
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_ALREADY_EXISTS: 'CUSTOMER_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // Category
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',

  // Modifier
  MODIFIER_GROUP_NOT_FOUND: 'MODIFIER_GROUP_NOT_FOUND',

  // Review
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_NOT_OWNED: 'REVIEW_NOT_OWNED',

  // Upload
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Merchant/User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  // SuperAdmin
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  MERCHANT_NOT_FOUND: 'MERCHANT_NOT_FOUND',
  UPGRADE_NOT_ALLOWED: 'UPGRADE_NOT_ALLOWED',
  ALREADY_ON_PLAN: 'ALREADY_ON_PLAN',

  // Wishlist
  WISHLIST_ITEM_EXISTS: 'WISHLIST_ITEM_EXISTS',

  // Cart
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_NOT_OWNED: 'CART_NOT_OWNED',

  // Auth Reset/Verify
  TOKEN_INVALID: 'TOKEN_INVALID',
  VERIFICATION_TOKEN_EXPIRED: 'VERIFICATION_TOKEN_EXPIRED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  PASSWORD_RESET_EXPIRED: 'PASSWORD_RESET_EXPIRED',

  // MFA
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_CODE_INVALID: 'MFA_CODE_INVALID',
  MFA_CODE_EXPIRED: 'MFA_CODE_EXPIRED',

  // Staff
  STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
  STAFF_INVITE_EXPIRED: 'STAFF_INVITE_EXPIRED',
  STAFF_INVITE_NOT_FOUND: 'STAFF_INVITE_NOT_FOUND',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Shipping & Tax
  ZONE_NOT_FOUND: 'ZONE_NOT_FOUND',
  RATE_NOT_FOUND: 'RATE_NOT_FOUND',
  TAX_RATE_NOT_FOUND: 'TAX_RATE_NOT_FOUND',
  SHIPPING_NOT_CALCULABLE: 'SHIPPING_NOT_CALCULABLE',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',

  // Price verification
  PRICE_MISMATCH: 'PRICE_MISMATCH',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  MODIFIER_NOT_FOUND: 'MODIFIER_NOT_FOUND',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  COUPON_NOT_APPLICABLE: 'COUPON_NOT_APPLICABLE',
  SHIPPING_OPTION_INVALID: 'SHIPPING_OPTION_INVALID',

  // Payment
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_PROVIDER_NOT_ENABLED: 'PAYMENT_PROVIDER_NOT_ENABLED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',

  // Returns
  RETURN_NOT_FOUND: 'RETURN_NOT_FOUND',
  RETURN_INVALID_STATUS: 'RETURN_INVALID_STATUS',
  RETURN_UNAUTHORIZED: 'RETURN_UNAUTHORIZED',

  // CMS
  CMS_PAGE_NOT_FOUND: 'CMS_PAGE_NOT_FOUND',

  // API Keys
  API_KEY_INVALID: 'API_KEY_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
